### ISSUE TITLE
Add {UMB}: {Umbrella}

### ISSUE THREAD

**Issue by leviadam** [Uniswap/default-token-list#746]
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0x6fC13EACE26590B80cCCAB1ba5d51890577D83B2
Token Name (from contract): Umbrella
Token Decimals (from contract): 18
Token Symbol (from contract): UMB
Uniswap V2 Pair Address of Token: 0xb1bbeea2da2905e6b0a30203aef55c399c53d042

Link to the official homepage of token: https://umb.network
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/umbrella-network/
